/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/pr2admin/desktop/tutorials/beginner/src/joint_states_listener/srv/ReturnJointStates.srv
 *
 */


#ifndef JOINT_STATES_LISTENER_MESSAGE_RETURNJOINTSTATES_H
#define JOINT_STATES_LISTENER_MESSAGE_RETURNJOINTSTATES_H

#include <ros/service_traits.h>


#include <joint_states_listener/ReturnJointStatesRequest.h>
#include <joint_states_listener/ReturnJointStatesResponse.h>


namespace joint_states_listener
{

struct ReturnJointStates
{

typedef ReturnJointStatesRequest Request;
typedef ReturnJointStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReturnJointStates
} // namespace joint_states_listener


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::joint_states_listener::ReturnJointStates > {
  static const char* value()
  {
    return "ce9bd2b56c904b190a782a08482fb4e9";
  }

  static const char* value(const ::joint_states_listener::ReturnJointStates&) { return value(); }
};

template<>
struct DataType< ::joint_states_listener::ReturnJointStates > {
  static const char* value()
  {
    return "joint_states_listener/ReturnJointStates";
  }

  static const char* value(const ::joint_states_listener::ReturnJointStates&) { return value(); }
};


// service_traits::MD5Sum< ::joint_states_listener::ReturnJointStatesRequest> should match 
// service_traits::MD5Sum< ::joint_states_listener::ReturnJointStates > 
template<>
struct MD5Sum< ::joint_states_listener::ReturnJointStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::joint_states_listener::ReturnJointStates >::value();
  }
  static const char* value(const ::joint_states_listener::ReturnJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::joint_states_listener::ReturnJointStatesRequest> should match 
// service_traits::DataType< ::joint_states_listener::ReturnJointStates > 
template<>
struct DataType< ::joint_states_listener::ReturnJointStatesRequest>
{
  static const char* value()
  {
    return DataType< ::joint_states_listener::ReturnJointStates >::value();
  }
  static const char* value(const ::joint_states_listener::ReturnJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::joint_states_listener::ReturnJointStatesResponse> should match 
// service_traits::MD5Sum< ::joint_states_listener::ReturnJointStates > 
template<>
struct MD5Sum< ::joint_states_listener::ReturnJointStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::joint_states_listener::ReturnJointStates >::value();
  }
  static const char* value(const ::joint_states_listener::ReturnJointStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::joint_states_listener::ReturnJointStatesResponse> should match 
// service_traits::DataType< ::joint_states_listener::ReturnJointStates > 
template<>
struct DataType< ::joint_states_listener::ReturnJointStatesResponse>
{
  static const char* value()
  {
    return DataType< ::joint_states_listener::ReturnJointStates >::value();
  }
  static const char* value(const ::joint_states_listener::ReturnJointStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JOINT_STATES_LISTENER_MESSAGE_RETURNJOINTSTATES_H
